### ISSUE TITLE
Support for anonymous users

### ISSUE THREAD

**Issue by chaps2** [dpi/rng#1]
Really like what you've done so far. But it looks to me like support for anonymous registrants isn't there yet despite this mention in the readme:

> Identity: any entity that has implemented a method for contact, core implements the User entity, although RNG provides another entity which is used for anonymous purposes.

Would love to see support for anonymous registrants in the near future!

**Comment by dpi** [comment]
Its coming. I'm working on two major features which need a little more time:

**Identities** other than Drupal users (anonymous users, etc)
**Messages**: multiple channels for sending communications (email, SMS, private message etc)

**Comment by dpi** [comment]
The latest round of updates adds support for anonymous users in the form of a contact. Contacts are provided by the (optional) [Identity](https://github.com/dpi/identity) module.

I'm currently working on making the UI seamless for referencing new contacts on the registration page. Until then, you can manually add new contacts at /identity/contact/add

**Comment by weizrd** [comment]
Hello, I was wondering which is the status on this.
It looks like a better alternative to Entity Registration, but anonymous still can't register themselves (so is not usable for me). Also, not all my users have emails, so maybe there would be a way to just skip that step alltogether and leave available an open workable visible form? (yeah, i know that this leaves an open door to duplicates, but I will take that chance)
Thank you

**Comment by dpi** [comment]
Hi @weizrd, take a look at [Identity](https://github.com/dpi/identity), theres some temporary documentation at https://github.com/dpi/identity/issues/1 . Since no verification is done on contacts in that module, you can use bogus emails if required. 

The key to registrants is they must be 'contactable' in some way. You can even create a custom Drupal entity type, and enable it as a new registrant type available to RNG (and take only phone numbers etc).

Please create new issues on that project.
