### ISSUE TITLE
Anonymous registrations

### ISSUE THREAD

**Issue by bitchkat** [dpi/rng#145]
I'm just getting starting with registrations on D8 and since the old entity_registration module is completely broken on D8, I'm giving rng a try.

For this site, the customer is pretty set on allowing users to register for events without creating accounts on the website.   I've installed and configured rng and rng_contact according to their respective quick start guides.

I can't get anonymous users to register because the "Register Self" permission can't be set for anonymous users.  
This is because rng.module has:
```
/**
 * Implements hook_form_alter().
 */
function rng_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'user_admin_permissions') {
    // Anonymous 'user' cannot register himself because it is a fake user.
    $form['permissions']['rng register self'][AccountInterface::ANONYMOUS_ROLE]['#disabled'] = TRUE;
    $form['permissions']['rng register self'][AccountInterface::ANONYMOUS_ROLE]['#access'] = FALSE;
  }
}
```

If I disable that code, I can set the "register self" permission for Anonymous and then they can register after creating a new Contact.

Did I miss something in my configuration that reenables the permission setting if rng_contact is installed?

**Comment by dpi** [comment]
Please see https://dpi.id.au/rng-contact-setup/ for the canonical guide on setting up anonymous registrants. The sections which you should be most aware of are **[Enable the contact type for your event types](https://dpi.id.au/rng-contact-setup/#enablethecontacttypeforyoureventtypes)** and **[Permissions](https://dpi.id.au/rng-contact-setup/#permissions)**.

The checkbox is disabled because anonymous agents dont actually map to user entities. I suggest you unset `rng register self` for anons in case it is repurposed in the future.
