### ISSUE TITLE
what does RNG stand for?

### ISSUE THREAD

**Issue by aaronbauman** [dpi/rng#150]
what does the acronym / initials mean?

**Comment by MegaChriz** [comment]
I think it stands for Registration Next Generation. At some point during the Drupal 8 development there was also an EntityNG concept:
http://www.drupalcontrib.org/api/drupal/drupal!core!lib!Drupal!Core!Entity!EntityNG.php/class/EntityNG/8

> Entity(..)NG classes are variants of the Entity(...) classes that implement the **next generation** (NG) entity field API.

**Comment by aaronbauman** [comment]
Oh yeah, i remember DBTNG.
Good call, i'm sure that's it.

**Comment by dpi** [comment]
Originally an internal project for Registrations and Groups, but any notion of Groups was mostly removed. A secondary meaning of Registration Next Generation was also intended, since many Drupal 8 subsystems also had this _NG_ moniker during development.

Though at this point, RNG the acronym does not currently stand for anything.
